#!/bin/bash

# utilize SLURM_ARRAY_TASK_ID from outside this script to parallelize this script over multiple GPUs
# check SLURM_ARRAY_TASK_ID because it won't exist in /rfanfs/
if [ ! -z ${SLURM_ARRAY_TASK_ID} ]
then
    export CUDA_VISIBLE_DEVICES=$(( ${SLURM_ARRAY_TASK_ID}%2 ))
fi

# the above %2 indicates how many cases you process parallelly
# it is limited by the number of GPUs in a node
# ml001 has 2 GPUs, ml004 and ml005 have 4 GPUs

# a single caseid or a text file with list of cases
# use a single caseid when running the below commands directly in a terminal
# use a caselist when "bsub < run_gpu_mask.lsf"
# caselist=1234
# caselist=/path/to/my/caselist.txt


if [ -f ${caselist} ]
then
    # LSF script, list of subjects
    id=`head -${SLURM_ARRAY_TASK_ID} ${caselist} | tail -1`
else
    # shell script, one subject
    id=${caselist}
fi


cluster=`hostname | grep pnl-.*.partners.org`
if [ -z $cluster ]
then
    source /data/pnl/soft/pnlpipe3/bashrc3-gpu
else
    source /rfanfs/pnl-zorro/software/pnlpipe3/bashrc3-gpu
fi


# for HD-BET structural masking
export LUIGI_CONFIG_PATH=/data/pnl/soft/pnlpipe3/luigi-pnlpipe/params/hcp/T2w_mask_params.cfg
/data/pnl/soft/pnlpipe3/luigi-pnlpipe/exec/ExecuteTask \
--bids-data-dir /data/pnl/U01_HCP_Psychosis/data_processing/BIDS/rawdata \
--t2-template "sub-*/ses-*/anat/*_T2w.nii.gz" \
-c $id -s 1 \
--task StructMask


# for CNN diffusion masking
# export LUIGI_CONFIG_PATH=/data/pnl/soft/pnlpipe3/luigi-pnlpipe/params/cte/cnn_dwi_mask_params.cfg
# /data/pnl/soft/pnlpipe3/luigi-pnlpipe/exec/ExecuteTask \
# --bids-data-dir /data/pnl/DIAGNOSE_CTE_U01/rawdata \
# --dwi-template "sub-*/ses-*/dwi/*_dwi.nii.gz" \
# -c $id -s 01 \
# --task CnnMask

